### PR TITLE
Switched arrows in DAG to point backwards in time

### PR DESCRIPTION
**Pull request by lb1a**
The image used in w4-d1 is pointing forward in time, not possible from a git point of view. I flipped them to point backwards. Only did this to the source svg image. Not sure how you create the actual image used in the book.

### CODE REVIEW

**Comment by lb1a** [comment]
Hm i just stumbled upon another image which points forwards. is this a general matter an done on purpose? Or should is reverse that image(s) also?

**Comment by cbx33** [comment]
It could very well be I got it wrong and went against convention
everywhere....or just made a mistake....I'll take a closer look in a bit.

**Comment by cbx33** [comment]
I think the arrows were to indicate time, not parenting.

**Comment by lb1a** [comment]
Yeah that's what it is, but i found that rather confusing. So could you maybe indicate that more clearly, that the arrows are representing time and not parenting. Or maybe to the parenting correct, but putting another big time arrow to maybe at the side. Like in a diagram or something like a time bar.

**Comment by cbx33** [comment]
That was exactly my thought. I'm not going to get to make these changes
within the next week or so, but I'll do my best when I get time.

**Comment by lb1a** [comment]
I'd appreciate that. So this PR is not useful any more, as it only affects one simple image. I'm gonna close it, but thanks for the discussion.

**Comment by cbx33** [comment]
No problem, hope you found GITT useful.

**Pull request closed without merging**
