### PR TITLE
Cleaned up the preamble and a few other bits

### PR DESCRIPTION
**Pull request by godbyk**
I moved the code from the preamble and commands.tex to a new document class.  This simplifies the gitt.tex file quite a bit.

I changed \input to \include in gitt.tex as \include will automatically insert the page breaks.

I tweaked the Makefile, also.  You need to run pdflatex multiple times to finalize the table of contents.  When you run it just once, it generates the table of contents, but doesn't include it in the PDF until a later pass.  I added some more files to the clean target (the files that LaTeX (re)generates each time it's run).

I also added a .gitignore file that ignores the files generated by LaTeX.

I created a callout environment to replace the verbose figure/tikzpicture environments you were using for the gray callout boxes.  The syntax for the callout environment is:

```
\begin{callout}{<type>}{<title>}
  The contents of the callout box.
\end{callout}
```

where `<type>` is printed along the left border of the callout box and `<title>` is printed along the top border.

I replaced all of the \begin{center} \* \* \* \end{center} bits with a new macro named \thoughtbreak.  We can make this macro a bit fancier in the future.

I set a default format for the Verbatim environments and removed the optional arguments from them in the .tex files.  That should make maintenance and new code easier to write.

### CODE REVIEW

**Comment by cbx33** [comment]
Awesome work - let me take a look and see about merging the sucker

On 16 May 2011 01:31, godbyk <
reply@reply.github.com>wrote:

> I moved the code from the preamble and commands.tex to a new document
> class.  This simplifies the gitt.tex file quite a bit.
> 
> I changed \input to \include in gitt.tex as \include will automatically
> insert the page breaks.
> 
> I tweaked the Makefile, also.  You need to run pdflatex multiple times to
> finalize the table of contents.  When you run it just once, it generates the
> table of contents, but doesn't include it in the PDF until a later pass.  I
> added some more files to the clean target (the files that LaTeX
> (re)generates each time it's run).
> 
> I also added a .gitignore file that ignores the files generated by LaTeX.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cbx33/gitt/pull/14

## 

Pete Savage - cbx33::silentk
http://geekdeck.wordpress.com

**Comment by jonasbb** [comment]
The changes are working well with two exceptions. There are two little graphic changes. I think they are not important. The grey boxes move a little to the left (or right?) and there is more space between the \* \* *.
Good work.

**Comment by godbyk** [comment]
Both changes that jonasbb mentions are deliberate.

The gray boxes were previously hanging into the right margin causing LaTeX to generate "Overfull hbox" warnings—LaTeX parlance for "the line is too long to fit in the margin!"  I moved the boxes 10 pt to the left so that the vertical box extends into the left margin.  This has the effect of aligning the left and right edges of the gray box with the margins (which looks better visually).

As for the asterisks, I figure those will be replaced with something a bit fancier in the future.  For now, \thoughtbreak is just a shortcut for the authors.

**Comment by jonasbb** [comment]
Yeah, as I  wrote. Its not really important.
I only wanted to mention this.

**Comment by cbx33** [comment]
Cool - been really busy at work, but hope to get to this later on tonight

On 17 May 2011 16:41, jonasbb <
reply@reply.github.com>wrote:

> Yeah, as I  wrote. Its not really important.
> I only wanted to mention this.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cbx33/gitt/pull/14#issuecomment-1191127

## 

Pete Savage - cbx33::silentk
http://geekdeck.wordpress.com

**Comment by cbx33** [comment]
This is excellent work!  Really awesome - things I tried so hard to do but couldn't!!!  I will be taking one last look and test through this tomorrow and then I'll merge.

A question, do you know how to sort out the Chapter Names at the top of the page.  They have a period mark in front of them, where I just removed the chapter numbers.  I would love for this to be sorted, but I have not got a clue where to start.  Any ideas?

**Comment by godbyk** [comment]
Oh, you mean the running heads?  Yeah, I can fix that for you.  I'll try to fix that later tonight or tomorrow.  Real work intrudes!

Let me know if you have any questions about any of the code.

**Comment by cbx33** [comment]
Please, if you would like, add yourself to the ack.tex file :)

**Comment by cbx33** [comment]
Is there a way to make the "code" sections in the Verbatim wrap, instead of me having to put the manual breaks in?

**Pull request merged**
