### PR TITLE
Mostly cosmetic/grammar tweaks

### PR DESCRIPTION
**Pull request by Gumnos**
Most should be pretty-much no-brainers, except perhaps for c3f59c41

### CODE REVIEW

**Comment by cbx33** [comment]
Thank you so much for these commits - how did you find the content of the book?

**Comment by Gumnos** [comment]
### Overall:

The book was a pretty good introduction to git.  Adding a storyline with the fake company went a long way to making sense of how some git features would be useful.  The submodule bit was a bit of a stretch, but better than anything else I've read on submodules (both the "why" and the "how/workflow").

### Suggested areas of improvement:
- One of the hardest areas to follow was the example "code" that was getting checked in/out. By using somewhat nonsense text, it's hard to keep a mental model of the code-base when changes are made, conflicts are introduced/resolved, etc.  Changing the examples to some sort of small Hello World code base, or using distinct files (a file of numbers, a file of spelled numbers, a file of letters, a file of aeronautic/phonetic/military alphabet "letter", etc) would allow the reader to more readily associate the content with the filename.  This might also help strengthen the submodule chapter, since the concept of a submodule makes little sense when dealing with random text.
- It would have been helpful for the examples to show the pain of (foolishly) rebasing a commit that has already been pushed: what to do when it happens, why you shouldn't let it happen, and who you should pummel if they _do_ rebase changes they've already pushed.  You touch on similar symptoms at the end of the section on applying patches (I believe something similar happens when rebased changes are pushed), but unifying those might help clarify the ominous warnings against doing it.

Thanks for a fun text on git.

**Comment by cbx33** [comment]
Hi Tim,

Thank you so much for taking the time to give me awesome feedback - I will
probably go back to it in a year and redo all of that :)
The random text was a little concern for me too - it grew and grew -
problem with Git is, if you change something all the IDs change and I was
too anal to "fudge" one of them :) All the GUI screenshots would have to be
re-done the graphics too.  I toyed with the idea of actually putting all
commands into a script and auto generating all of the output so I could do
things like that. But it was a lot of work for not a whole amount of payoff.

I get what you are saying about the rebasing. Maybe I could link to that
other section :) - Nice idea.

Glad you enjoyed it and please, if you think it is worth it, spread the
word :)

Thanks again for the time taken to comment and fix issues

Pete

## 

Pete Savage - cbx33::silentk

_BOOKS_
_Emblem Divide (Novel - Complete) - *http://emblemdivide.com/
*Git in the Trenches (Technical Book) - *http://cbx33.github.com/gitt/
*Alchemy Reigns_ _(Novel - Work in progress) -_
http://alchemyreigns.wordpress.com/

**Comment by Gumnos** [comment]
I tried to distill my commentary to the most essential bits. I'm concurrently a technical reviewer for the upcoming Practical Vim book (by Drew Neil, to be published by Pragmatic Programmers), and wanted to make sure I didn't blast you with the same firehose of picayune critique that he's requested of me.  Though my expertise in Vim _far_ exceeds any claim I have to expertise in git. :-)

**Pull request merged**
